---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    networks: 
      - torrenting
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/pi/.config/sonarr:/config
      - /home/pi/media/shows:/tv
      - /home/pi/downloads/sonarr:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
networks:
  torrenting:
    external: true
