version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    networks: 
      - torrenting
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/pi/.config/radarr:/config
      - /home/pi/media/movies:/movies
      - /home/pi/downloads/radarr:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
networks:
  torrenting:
    external: true
